apiVersion: v1
kind: Service
metadata:
  name: store-engine-dto-validator-service
spec:
  selector:
    app: store-engine-dto-validator-ms
  ports:
    - protocol: TCP
      name: validator-tcp-port
      port: 3002
      targetPort: 3002
  type: NodePort
